version: '3.8'
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-consumption-app
    ports:
      - "8080:8080"
    environment:
      - MAVEN_OPTS=-Xmx512m
    command: java -jar /app/cloud-consumption-app-1.0-SNAPSHOT.jar
