version: '3'
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Port-Mapping zwischen Host und Container
    volumes:
      - .:/app  # Bind-Mount für das Projektverzeichnis
    environment:
      - ENV_VARIABLE=production  # Beispiel für Umgebungsvariablen
    command: java -jar your-app.jar  # Start der Java-Anwendung
