version: '3.8'
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENV_VARIABLE=production
    command: mvn clean package -DskipTests && java -jar target/your-app.jar
