name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Change to the directory where Dockerfile and docker-compose.yml exist
      - name: Set working directory
        run: cd main

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # Ensure Docker is up and running
      - name: Ensure Docker is running
        run: sudo systemctl start docker

      # Build and run Docker Compose in detached mode
      - name: Run docker-compose up
        run: |
          cd main && docker-compose up --build -d

      # Optional: Run tests (if required)
      - name: Run tests
        run: |
          cd main && docker-compose exec my_service mvn test

      # Tear down Docker Compose after tests are done
      - name: Tear down
        if: always()
        run: |
          cd main && docker-compose down
