
name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      # Install Docker Compose
      - name: Set up Docker Compose
        run: |
          
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # Build and run Docker Compose in detached mode
      - name: Run docker-compose up
        run: docker-compose up --build -d


      - name: Tear down
        run: docker-compose down