name: Docker Compose Integration Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Run Docker Compose
        run: |
          docker-compose up --build -d
          sleep 15

      - name: Run Unit Tests
        run: mvn test

      - name: Check Logs of My Application
        run: docker logs $(docker-compose ps -q my_service)

      - name: Push Docker Image to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: your-dockerhub-username/cloud-consumption-app:latest
